require('core.plugins')
require('config.coc')
require('config.lualine')
require('config.nvimtree')
require('config.buffer_line')
require('config.telescope')
require('config.theme')
require('config.treesitter')
require('config.dap_python')
require('config.dap_cpp')
require('config.gitsigns')

require('core.options')
require('core.mappings')
require('core.autocmds')
